# Calcular Trafico

In [1]:
import pandas as pd

df_traf = pd.read_csv("datos/trafico2021_2023.csv")

df_traf

           Unnamed: 0    id                fecha tipo_elem  intensidad error
0               11892  1009  2021-01-01 00:00:00       M30         180     N
1               11893  1009  2021-01-01 00:15:00       M30         108     N
2               11894  1009  2021-01-01 00:30:00       M30         108     N
3               11895  1009  2021-01-01 00:45:00       M30         672     N
4               11896  1009  2021-01-01 01:00:00       M30        1452     N
...               ...   ...                  ...       ...         ...   ...
276996270   424091712  4738  2023-12-31 22:45:00       URB          20     N
276996271   424091713  4738  2023-12-31 23:00:00       URB          30     N
276996272   424091714  4738  2023-12-31 23:15:00       URB          20     N
276996273   424091715  4738  2023-12-31 23:30:00       URB          22     N
276996274   424091716  4738  2023-12-31 23:45:00       URB          12     N

[276996275 rows x 6 columns]

In [2]:
df_traf = df_traf.drop(columns='Unnamed: 0')
df_traf

             id                fecha tipo_elem  intensidad error
0          1009  2021-01-01 00:00:00       M30         180     N
1          1009  2021-01-01 00:15:00       M30         108     N
2          1009  2021-01-01 00:30:00       M30         108     N
3          1009  2021-01-01 00:45:00       M30         672     N
4          1009  2021-01-01 01:00:00       M30        1452     N
...         ...                  ...       ...         ...   ...
276996270  4738  2023-12-31 22:45:00       URB          20     N
276996271  4738  2023-12-31 23:00:00       URB          30     N
276996272  4738  2023-12-31 23:15:00       URB          20     N
276996273  4738  2023-12-31 23:30:00       URB          22     N
276996274  4738  2023-12-31 23:45:00       URB          12     N

[276996275 rows x 5 columns]

In [3]:
df_ubic = pd.read_csv("datos/ubicaciones_sensores_trafico.csv")

df_ubic = df_ubic.drop(columns='Unnamed: 0')

df_ubic

,tipo_elem,distrito,id,cod_cent,nombre,utm_x,utm_y,longitud,latitud
0,URB,4.0,3840,01001,Jose Ortega y Gasset E-O - Pº Castellana-Serrano,441615.343346657,4475767.9421385,-3.6883232754856,40.4305018691825
1,URB,4.0,3841,01002,Jose Ortega y Gasset O-E - Serrano-Pº Castellana,441705.882339595,4475769.68733175,-3.68725610305613,40.4305239406404
2,URB,1.0,3842,01003,Pº Recoletos N-S - Almirante-Prim,441319.371258338,4474841.15423716,-3.6917268449043,40.4221320929972
3,URB,4.0,3843,01004,Pº Recoletos S-N - Pl. Cibeles- Recoletos,441301.63298559,4474763.7275141,-3.69192878230734,40.4214333442836
4,URB,4.0,3844,01005,(AFOROS) Pº Castellana S-N - Eduardo Dato - P...,441605.765071902,4476132.13924728,-3.68846965033102,40.4337820578943
...,...,...,...,...,...,...,...,...,...
5423,URB,16.0,11235,72406,Av. Secundino Zuazo - César Cort Boti-Gta. Jos...,448.388.147.010.537,448.286.747.130.414,-360.905.755.542.047,404.949.062.864.003
5424,URB,16.0,11276,72407,Av. Manuel Fraga Iribarne (CARRIL BUS) - AV. M...,44.843.325.332.997,448.251.275.311.267,-360.849.642.913.409,404.917.136.031.255
5425,URB,16.0,11277,72408,Av. Manuel Fraga Iribarne (CARRIL BUS) - Jordi...,448.436.665.701.945,448.282.732.568.793,-360.848.176.299.328,404.945.476.496.166
5426,URB,16.0,11279,72409,Secundino Zuazo (CARRIL BUS) - Josefina Aldeco...,447.824.682.462.605,448.294.459.287.868,-361.571.283.696.763,404.955.658.049.048
5427,URB,16.0,11278,72410,Secundino Zuazo (CARRIL BUS) - Fina de Calderó...,447.748.942.805.197,448.294.078.306.391,-361.660.626.563.366,40.495.526.719.101

# Asignar Distrito a las mediciones

In [5]:
df_ubic = df_ubic.drop(columns=['tipo_elem', 'cod_cent', 'nombre', 'utm_x', 'utm_y', 'longitud', 'latitud'])

df_traf = pd.merge(df_traf, df_ubic, on='id', how='left')

df_traf

             id                fecha tipo_elem  intensidad error  distrito
0          1009  2021-01-01 00:00:00       M30         180     N       9.0
1          1009  2021-01-01 00:00:00       M30         180     N       9.0
2          1009  2021-01-01 00:15:00       M30         108     N       9.0
3          1009  2021-01-01 00:15:00       M30         108     N       9.0
4          1009  2021-01-01 00:30:00       M30         108     N       9.0
...         ...                  ...       ...         ...   ...       ...
314532569  4738  2023-12-31 22:45:00       URB          20     N       8.0
314532570  4738  2023-12-31 23:00:00       URB          30     N       8.0
314532571  4738  2023-12-31 23:15:00       URB          20     N       8.0
314532572  4738  2023-12-31 23:30:00       URB          22     N       8.0
314532573  4738  2023-12-31 23:45:00       URB          12     N       8.0

[314532574 rows x 6 columns]

In [8]:
df_traf['distrito'].unique()

array([ 9., 12.,  2., 11.,  3.,  5.,  8.,  6.,  4., 16., 18., 14., 21.,
       nan, 19.,  1.])

# Eliminar datos incorrectos

In [10]:
df_traf = df_traf[df_traf['error'] != 'E']
df_traf
#No ha eliminado nada

             id                fecha tipo_elem  intensidad error  distrito
0          1009  2021-01-01 00:00:00       M30         180     N       9.0
1          1009  2021-01-01 00:00:00       M30         180     N       9.0
2          1009  2021-01-01 00:15:00       M30         108     N       9.0
3          1009  2021-01-01 00:15:00       M30         108     N       9.0
4          1009  2021-01-01 00:30:00       M30         108     N       9.0
...         ...                  ...       ...         ...   ...       ...
314532569  4738  2023-12-31 22:45:00       URB          20     N       8.0
314532570  4738  2023-12-31 23:00:00       URB          30     N       8.0
314532571  4738  2023-12-31 23:15:00       URB          20     N       8.0
314532572  4738  2023-12-31 23:30:00       URB          22     N       8.0
314532573  4738  2023-12-31 23:45:00       URB          12     N       8.0

[314532574 rows x 6 columns]

In [11]:
df_traf.drop(columns='error', inplace=True)
df_traf

             id                fecha tipo_elem  intensidad  distrito
0          1009  2021-01-01 00:00:00       M30         180       9.0
1          1009  2021-01-01 00:00:00       M30         180       9.0
2          1009  2021-01-01 00:15:00       M30         108       9.0
3          1009  2021-01-01 00:15:00       M30         108       9.0
4          1009  2021-01-01 00:30:00       M30         108       9.0
...         ...                  ...       ...         ...       ...
314532569  4738  2023-12-31 22:45:00       URB          20       8.0
314532570  4738  2023-12-31 23:00:00       URB          30       8.0
314532571  4738  2023-12-31 23:15:00       URB          20       8.0
314532572  4738  2023-12-31 23:30:00       URB          22       8.0
314532573  4738  2023-12-31 23:45:00       URB          12       8.0

[314532574 rows x 5 columns]

# Exportación de nuevo

In [12]:
df_traf.to_csv('datos/trafico2021_2023.csv', index=False)

Baja de 12 GB a 11