# Calcular Trafico

In [1]:
import pandas as pd

df_traf = pd.read_csv("datos/trafico2021_2023.csv")

df_traf

             id                fecha tipo_elem  intensidad  distrito
0          1009  2021-01-01 00:00:00       M30         180       9.0
1          1009  2021-01-01 00:00:00       M30         180       9.0
2          1009  2021-01-01 00:15:00       M30         108       9.0
3          1009  2021-01-01 00:15:00       M30         108       9.0
4          1009  2021-01-01 00:30:00       M30         108       9.0
...         ...                  ...       ...         ...       ...
314532569  4738  2023-12-31 22:45:00       URB          20       8.0
314532570  4738  2023-12-31 23:00:00       URB          30       8.0
314532571  4738  2023-12-31 23:15:00       URB          20       8.0
314532572  4738  2023-12-31 23:30:00       URB          22       8.0
314532573  4738  2023-12-31 23:45:00       URB          12       8.0

[314532574 rows x 5 columns]

## Primero eliminar duplicados.

In [21]:
df_traf = df_traf.drop_duplicates().reset_index()
df_traf

,index,id,fecha,tipo_elem,intensidad,distrito
0,0,1009,2021-01-01 00:00:00,M30,180,9.0
1,2,1009,2021-01-01 00:15:00,M30,108,9.0
2,4,1009,2021-01-01 00:30:00,M30,108,9.0
3,6,1009,2021-01-01 00:45:00,M30,672,9.0
4,8,1009,2021-01-01 01:00:00,M30,1452,9.0
...,...,...,...,...,...,...
277262800,314532569,4738,2023-12-31 22:45:00,URB,20,8.0
277262801,314532570,4738,2023-12-31 23:00:00,URB,30,8.0
277262802,314532571,4738,2023-12-31 23:15:00,URB,20,8.0
277262803,314532572,4738,2023-12-31 23:30:00,URB,22,8.0
277262804,314532573,4738,2023-12-31 23:45:00,URB,12,8.0

Se reduce considerablemente el numero de filas

## Calcular la suma de intensidad (numero total de coches que pasa en 1h por ese punto)

In [22]:
# Supongamos que 'df' es tu DataFrame
df_traf['fecha'] = pd.to_datetime(df_traf['fecha'])

# Eliminamos los minutos y segundos de la fecha
df_traf['fecha'] = df_traf['fecha'].apply(lambda x: x.replace(minute=0, second=0))

df_traf.set_index('fecha', inplace=True)


# CALCULO
# Agrupamos por id, tipo_elem, distrito y fecha, y sumamos la intensidad
df_calculado = df_traf.groupby(['id', 'tipo_elem', 'distrito', df_traf.index]).intensidad.sum().reset_index()

# Cambiamos el formato de la fecha para que muestre hasta los segundos
df_calculado['fecha'] = df_calculado['fecha'].dt.strftime('%Y-%m-%d %H:%M:%S')

df_calculado

             id tipo_elem  distrito                fecha  intensidad
0          1009       C30       9.0  2022-12-01 09:00:00         420
1          1009       C30       9.0  2022-12-01 10:00:00        1680
2          1009       C30       9.0  2022-12-01 11:00:00        1680
3          1009       C30       9.0  2022-12-01 12:00:00        1680
4          1009       C30       9.0  2022-12-01 13:00:00        1680
...         ...       ...       ...                  ...         ...
70777069  11283       URB       5.0  2023-11-30 19:00:00         702
70777070  11283       URB       5.0  2023-11-30 20:00:00         519
70777071  11283       URB       5.0  2023-11-30 21:00:00         227
70777072  11283       URB       5.0  2023-11-30 22:00:00         142
70777073  11283       URB       5.0  2023-11-30 23:00:00          93

[70777074 rows x 5 columns]

In [23]:
df_calculado.to_csv("datos/trafico_calculado_intensidad_hora.csv")

De 277M a 77M

# Pruebas

In [18]:
df_reducido = df_traf.head(40)
df_reducido

      id                fecha tipo_elem  intensidad  distrito
0   1009  2021-01-01 00:00:00       M30         180       9.0
1   1009  2021-01-01 00:00:00       M30         180       9.0
2   1009  2021-01-01 00:15:00       M30         108       9.0
3   1009  2021-01-01 00:15:00       M30         108       9.0
4   1009  2021-01-01 00:30:00       M30         108       9.0
5   1009  2021-01-01 00:30:00       M30         108       9.0
6   1009  2021-01-01 00:45:00       M30         672       9.0
7   1009  2021-01-01 00:45:00       M30         672       9.0
8   1009  2021-01-01 01:00:00       M30        1452       9.0
9   1009  2021-01-01 01:00:00       M30        1452       9.0
10  1009  2021-01-01 01:15:00       M30        2340       9.0
11  1009  2021-01-01 01:15:00       M30        2340       9.0
12  1009  2021-01-01 01:30:00       M30        2232       9.0
13  1009  2021-01-01 01:30:00       M30        2232       9.0
14  1009  2021-01-01 01:45:00       M30        2448       9.0
15  1009  2021-01-01 01:45:00       M30        2448       9.0
16  1009  2021-01-01 02:00:00       M30        1368       9.0
17  1009  2021-01-01 02:00:00       M30        1368       9.0
18  1009  2021-01-01 02:15:00       M30         336       9.0
19  1009  2021-01-01 02:15:00       M30         336       9.0
20  1009  2021-01-01 02:30:00       M30         204       9.0
21  1009  2021-01-01 02:30:00       M30         204       9.0
22  1009  2021-01-01 02:45:00       M30         156       9.0
23  1009  2021-01-01 02:45:00       M30         156       9.0
24  1009  2021-01-01 03:00:00       M30          60       9.0
25  1009  2021-01-01 03:00:00       M30          60       9.0
26  1009  2021-01-01 03:15:00       M30         180       9.0
27  1009  2021-01-01 03:15:00       M30         180       9.0
28  1009  2021-01-01 03:30:00       M30         108       9.0
29  1009  2021-01-01 03:30:00       M30         108       9.0
30  1009  2021-01-01 03:45:00       M30         168       9.0
31  1009  2021-01-01 03:45:00       M30         168       9.0
32  1009  2021-01-01 04:00:00       M30         240       9.0
33  1009  2021-01-01 04:00:00       M30         240       9.0
34  1009  2021-01-01 04:15:00       M30         108       9.0
35  1009  2021-01-01 04:15:00       M30         108       9.0
36  1009  2021-01-01 04:30:00       M30           0       9.0
37  1009  2021-01-01 04:30:00       M30           0       9.0
38  1009  2021-01-01 04:45:00       M30          24       9.0
39  1009  2021-01-01 04:45:00       M30          24       9.0

In [19]:
df_reducido = df_reducido.drop_duplicates().reset_index()
df_reducido

    index    id                fecha tipo_elem  intensidad  distrito
0       0  1009  2021-01-01 00:00:00       M30         180       9.0
1       2  1009  2021-01-01 00:15:00       M30         108       9.0
2       4  1009  2021-01-01 00:30:00       M30         108       9.0
3       6  1009  2021-01-01 00:45:00       M30         672       9.0
4       8  1009  2021-01-01 01:00:00       M30        1452       9.0
5      10  1009  2021-01-01 01:15:00       M30        2340       9.0
6      12  1009  2021-01-01 01:30:00       M30        2232       9.0
7      14  1009  2021-01-01 01:45:00       M30        2448       9.0
8      16  1009  2021-01-01 02:00:00       M30        1368       9.0
9      18  1009  2021-01-01 02:15:00       M30         336       9.0
10     20  1009  2021-01-01 02:30:00       M30         204       9.0
11     22  1009  2021-01-01 02:45:00       M30         156       9.0
12     24  1009  2021-01-01 03:00:00       M30          60       9.0
13     26  1009  2021-01-01 03:15:00       M30         180       9.0
14     28  1009  2021-01-01 03:30:00       M30         108       9.0
15     30  1009  2021-01-01 03:45:00       M30         168       9.0
16     32  1009  2021-01-01 04:00:00       M30         240       9.0
17     34  1009  2021-01-01 04:15:00       M30         108       9.0
18     36  1009  2021-01-01 04:30:00       M30           0       9.0
19     38  1009  2021-01-01 04:45:00       M30          24       9.0

In [20]:
df = df_reducido

# Supongamos que 'df' es tu DataFrame
df['fecha'] = pd.to_datetime(df['fecha'])

# Eliminamos los minutos y segundos de la fecha
df['fecha'] = df['fecha'].apply(lambda x: x.replace(minute=0, second=0))

df.set_index('fecha', inplace=True)

# Agrupamos por id, tipo_elem, distrito y fecha, y sumamos la intensidad
df_resumen = df.groupby(['id', 'tipo_elem', 'distrito', df.index]).intensidad.sum().reset_index()

# Cambiamos el formato de la fecha para que muestre hasta los segundos
df_resumen['fecha'] = df_resumen['fecha'].dt.strftime('%Y-%m-%d %H:%M:%S')

(df_resumen)

     id tipo_elem  distrito                fecha  intensidad
0  1009       M30       9.0  2021-01-01 00:00:00        1068
1  1009       M30       9.0  2021-01-01 01:00:00        8472
2  1009       M30       9.0  2021-01-01 02:00:00        2064
3  1009       M30       9.0  2021-01-01 03:00:00         516
4  1009       M30       9.0  2021-01-01 04:00:00         372

In [24]:
df_resumen.to_csv("datos/prueba_calculo_intensidad.csv")