# Juntar los datos finales

## Datos Meteo y Contaminación

In [46]:
import pandas as pd

df_meteo = pd.read_csv("datos/CONT_METEO_REDUCIDO_2021_2024.csv")

df_meteo.drop(columns='Unnamed: 0')

df_meteo

,Unnamed: 0,ESTACION,DISTRITO,FECHA_HORA,NO,NO2,NOx,PM10,PM2_5,TEMP,HUM_REL,PRECIPITACION,PRES_BARIOMETRICA,RAD_SOL,DIR_VIENT,VEL_VIENT
0,0,8,3,2021-01-01 01:00:00,4.0,23.0,28.0,8.0,7.0,3.3,92.0,NaN,NaN,NaN,NaN,NaN
1,1,8,3,2021-01-01 02:00:00,6.0,36.0,46.0,12.0,10.0,3.2,89.0,NaN,NaN,NaN,NaN,NaN
2,2,8,3,2021-01-01 03:00:00,2.0,19.0,22.0,5.0,4.0,3.8,83.0,NaN,NaN,NaN,NaN,NaN
3,3,8,3,2021-01-01 04:00:00,1.0,12.0,13.0,5.0,4.0,4.0,83.0,NaN,NaN,NaN,NaN,NaN
4,4,8,3,2021-01-01 05:00:00,1.0,12.0,13.0,1.0,1.0,3.9,81.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338953,338953,60,8,2023-12-31 20:00:00,5.0,30.0,37.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338954,338954,60,8,2023-12-31 21:00:00,6.0,35.0,44.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338955,338955,60,8,2023-12-31 22:00:00,4.0,37.0,44.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338956,338956,60,8,2023-12-31 23:00:00,2.0,20.0,23.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338957,338957,60,8,2023-12-31 00:00:00,2.0,15.0,19.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Datos Trafico

In [47]:
df_traf = pd.read_csv("datos/trafico_calculado_por_distrito.csv")

df_traf

        distrito                fecha  intensidad
0            1.0  2021-11-19 14:00:00          30
1            1.0  2021-11-21 11:00:00         120
2            1.0  2021-11-21 12:00:00         930
3            1.0  2021-11-21 13:00:00        3126
4            1.0  2021-11-21 14:00:00        4391
...          ...                  ...         ...
383172      21.0  2023-12-31 19:00:00        1512
383173      21.0  2023-12-31 20:00:00        1455
383174      21.0  2023-12-31 21:00:00         879
383175      21.0  2023-12-31 22:00:00         416
383176      21.0  2023-12-31 23:00:00         213

[383177 rows x 3 columns]

## Comprobaciones

In [48]:
df_traf['distrito'].value_counts()

distrito
3.0     26279
8.0     26279
9.0     26279
14.0    26279
2.0     26277
12.0    26277
4.0     26275
5.0     26275
6.0     26272
16.0    26271
21.0    26269
18.0    26248
11.0    26238
19.0    23257
1.0     18402
Name: count, dtype: int64

In [49]:
df_meteo['DISTRITO'].value_counts()

DISTRITO
5     26232
8     26217
16    26213
6     26206
4     26196
12    26136
18    26125
11    26122
3     26070
21    25938
2     25915
14    25844
9     25744
Name: count, dtype: int64

# Juntar

## Primero restar una hora a los datos de trafico para poder juntarlos

Porque la medicion de las 17 de contaminación ha influido el trafico durante la hora 16

In [50]:
# Convertimos la columna 'fecha' a tipo datetime
df_traf['fecha'] = pd.to_datetime(df_traf['fecha'])

# Restamos una hora a la columna 'fecha'
df_traf['fecha'] = df_traf['fecha'] - pd.Timedelta(hours=1)

df_traf

        distrito               fecha  intensidad
0            1.0 2021-11-19 13:00:00          30
1            1.0 2021-11-21 10:00:00         120
2            1.0 2021-11-21 11:00:00         930
3            1.0 2021-11-21 12:00:00        3126
4            1.0 2021-11-21 13:00:00        4391
...          ...                 ...         ...
383172      21.0 2023-12-31 18:00:00        1512
383173      21.0 2023-12-31 19:00:00        1455
383174      21.0 2023-12-31 20:00:00         879
383175      21.0 2023-12-31 21:00:00         416
383176      21.0 2023-12-31 22:00:00         213

[383177 rows x 3 columns]

## Juntar

In [51]:
df_traf['distrito'] = df_traf['distrito'].astype(int)
df_traf

        distrito               fecha  intensidad
0              1 2021-11-19 13:00:00          30
1              1 2021-11-21 10:00:00         120
2              1 2021-11-21 11:00:00         930
3              1 2021-11-21 12:00:00        3126
4              1 2021-11-21 13:00:00        4391
...          ...                 ...         ...
383172        21 2023-12-31 18:00:00        1512
383173        21 2023-12-31 19:00:00        1455
383174        21 2023-12-31 20:00:00         879
383175        21 2023-12-31 21:00:00         416
383176        21 2023-12-31 22:00:00         213

[383177 rows x 3 columns]

In [52]:
df_traf.dtypes

distrito               int64
fecha         datetime64[ns]
intensidad             int64
dtype: object

In [53]:
df_meteo['FECHA_HORA'] = pd.to_datetime(df_meteo['FECHA_HORA'])
df_meteo.dtypes

Unnamed: 0                    int64
ESTACION                      int64
DISTRITO                      int64
FECHA_HORA           datetime64[ns]
NO                          float64
NO2                         float64
NOx                         float64
PM10                        float64
PM2_5                       float64
TEMP                        float64
HUM_REL                     float64
PRECIPITACION               float64
PRES_BARIOMETRICA           float64
RAD_SOL                     float64
DIR_VIENT                   float64
VEL_VIENT                   float64
dtype: object

In [54]:
# Supongamos que df1 es tu DataFrame izquierdo y df2 es tu DataFrame derecho

df_traf = df_traf.rename(columns={'distrito': 'DISTRITO'})
df_traf = df_traf.rename(columns={'fecha': 'FECHA_HORA'})


df_final = pd.merge(df_meteo, df_traf, on=['DISTRITO', 'FECHA_HORA'], how='left')


df_final

,Unnamed: 0,ESTACION,DISTRITO,FECHA_HORA,NO,NO2,NOx,PM10,PM2_5,TEMP,HUM_REL,PRECIPITACION,PRES_BARIOMETRICA,RAD_SOL,DIR_VIENT,VEL_VIENT,intensidad
0,0,8,3,2021-01-01 01:00:00,4.0,23.0,28.0,8.0,7.0,3.3,92.0,NaN,NaN,NaN,NaN,NaN,45825.0
1,1,8,3,2021-01-01 02:00:00,6.0,36.0,46.0,12.0,10.0,3.2,89.0,NaN,NaN,NaN,NaN,NaN,22156.0
2,2,8,3,2021-01-01 03:00:00,2.0,19.0,22.0,5.0,4.0,3.8,83.0,NaN,NaN,NaN,NaN,NaN,16157.0
3,3,8,3,2021-01-01 04:00:00,1.0,12.0,13.0,5.0,4.0,4.0,83.0,NaN,NaN,NaN,NaN,NaN,13711.0
4,4,8,3,2021-01-01 05:00:00,1.0,12.0,13.0,1.0,1.0,3.9,81.0,NaN,NaN,NaN,NaN,NaN,29779.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338953,338953,60,8,2023-12-31 20:00:00,5.0,30.0,37.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53737.0
338954,338954,60,8,2023-12-31 21:00:00,6.0,35.0,44.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16343.0
338955,338955,60,8,2023-12-31 22:00:00,4.0,37.0,44.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11011.0
338956,338956,60,8,2023-12-31 23:00:00,2.0,20.0,23.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338957,338957,60,8,2023-12-31 00:00:00,2.0,15.0,19.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17705.0

In [55]:
print(df_traf.loc[(df_traf['FECHA_HORA'] == '2021-01-01 03:00:00') & (df_traf['DISTRITO'] == 3)])

       DISTRITO          FECHA_HORA  intensidad
44683         3 2021-01-01 03:00:00       16157

In [56]:
df_final.to_csv('datos/DATOS_FINALES.csv', index=False)  # index=False para no incluir los índices como una columna adicional