# Datos Meteo

## Juntar

In [46]:
import pandas as pd

df1 = pd.read_csv("datos/meteo/2021/ene_meteo21.csv", sep=';')
df2 = pd.read_csv("datos/meteo/2021/feb_meteo21.csv", sep=';')
df3 = pd.read_csv("datos/meteo/2021/mar_meteo21.csv", sep=';')
df4 = pd.read_csv("datos/meteo/2021/abr_meteo21.csv", sep=';')
df5 = pd.read_csv("datos/meteo/2021/may_meteo21.csv", sep=';')
df6 = pd.read_csv("datos/meteo/2021/jun_meteo21.csv", sep=';')
df7 = pd.read_csv("datos/meteo/2021/jul_meteo21.csv", sep=';')
df8 = pd.read_csv("datos/meteo/2021/ago_meteo21.csv", sep=';')
df9 = pd.read_csv("datos/meteo/2021/sep_meteo21.csv", sep=';')
df10 = pd.read_csv("datos/meteo/2021/oct_meteo21.csv", sep=';')
df11 = pd.read_csv("datos/meteo/2021/nov_meteo21.csv", sep=';')
df12 = pd.read_csv("datos/meteo/2021/dic_meteo21.csv", sep=';')

print(list(df1.columns) == list(df2.columns) == list(df3.columns) == list(df4.columns) == list(df5.columns) == list(df6.columns) == list(df7.columns) == list(df8.columns) == list(df9.columns) == list(df10.columns) == list(df11.columns) == list(df12.columns))

df2021 = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12], ignore_index=True)

del [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12]

df2021.shape

True

(31368, 56)

In [47]:
df1 = pd.read_csv("datos/meteo/2022/ene_meteo22.csv", sep=';')
df2 = pd.read_csv("datos/meteo/2022/feb_meteo22.csv", sep=';')
df3 = pd.read_csv("datos/meteo/2022/mar_meteo22.csv", sep=';')
df4 = pd.read_csv("datos/meteo/2022/abr_meteo22.csv", sep=';')
df5 = pd.read_csv("datos/meteo/2022/may_meteo22.csv", sep=';')
df6 = pd.read_csv("datos/meteo/2022/jun_meteo22.csv", sep=';')
df7 = pd.read_csv("datos/meteo/2022/jul_meteo22.csv", sep=';')
df8 = pd.read_csv("datos/meteo/2022/ago_meteo22.csv", sep=';')
df9 = pd.read_csv("datos/meteo/2022/sep_meteo22.csv", sep=';')
df10 = pd.read_csv("datos/meteo/2022/oct_meteo22.csv", sep=';')
df11 = pd.read_csv("datos/meteo/2022/nov_meteo22.csv", sep=';')
df12 = pd.read_csv("datos/meteo/2022/dic_meteo22.csv", sep=';')

print(list(df1.columns) == list(df2.columns) == list(df3.columns) == list(df4.columns) == list(df5.columns) == list(df6.columns) == list(df7.columns) == list(df8.columns) == list(df9.columns) == list(df10.columns) == list(df11.columns) == list(df12.columns))

df2022 = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12], ignore_index=True)

del [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12]

df2022.shape

True

(26510, 56)

In [48]:
df1 = pd.read_csv("datos/meteo/2023/ene_meteo23.csv", sep=';')
df2 = pd.read_csv("datos/meteo/2023/feb_meteo23.csv", sep=';')
df3 = pd.read_csv("datos/meteo/2023/mar_meteo23.csv", sep=';')
df4 = pd.read_csv("datos/meteo/2023/abr_meteo23.csv", sep=';')
df5 = pd.read_csv("datos/meteo/2023/may_meteo23.csv", sep=';')
df6 = pd.read_csv("datos/meteo/2023/jun_meteo23.csv", sep=';')
df7 = pd.read_csv("datos/meteo/2023/jul_meteo23.csv", sep=';')
df8 = pd.read_csv("datos/meteo/2023/ago_meteo23.csv", sep=';')
df9 = pd.read_csv("datos/meteo/2023/sep_meteo23.csv", sep=';')
df10 = pd.read_csv("datos/meteo/2023/oct_meteo23.csv", sep=';')
df11 = pd.read_csv("datos/meteo/2023/nov_meteo23.csv", sep=';')
df12 = pd.read_csv("datos/meteo/2023/dic_meteo23.csv", sep=';')

print(list(df1.columns) == list(df2.columns) == list(df3.columns) == list(df4.columns) == list(df5.columns) == list(df6.columns) == list(df7.columns) == list(df8.columns) == list(df9.columns) == list(df10.columns) == list(df11.columns) == list(df12.columns))

df2023 = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12], ignore_index=True)

del [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12]

df2023.shape

True

(32293, 56)

In [49]:
print(list(df2021.columns) == list(df2022.columns) == list(df2023.columns))

True

In [50]:
df = pd.concat([df2021, df2022, df2023])

del [df2021, df2022, df2023]

## Creación de la columna Fecha

In [51]:
df['FECHA'] = df['DIA'].astype(str) + '/' + df['MES'].astype(str) + '/' + df['ANO'].astype(str)

df = df.drop(columns=['ANO', 'MES', 'DIA'])

df['FECHA'] = pd.to_datetime(df['FECHA'], format='%d/%m/%Y')

df

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,H01,V01,H02,V02,H03,...,V20,H21,V21,H22,V22,H23,V23,H24,V24,FECHA
0,28,79,102,81,28079102_81_98,0.98,V,1.40,V,1.55,...,V,3.65,V,2.13,V,0.97,V,0.58,V,2021-01-01
1,28,79,102,81,28079102_81_98,1.18,V,1.65,V,1.17,...,V,1.22,V,0.38,V,0.45,V,0.75,V,2021-01-02
2,28,79,102,81,28079102_81_98,0.62,V,0.55,V,0.73,...,V,1.53,V,2.20,V,1.80,V,1.27,V,2021-01-03
3,28,79,102,81,28079102_81_98,1.93,V,1.82,V,0.72,...,V,1.10,V,1.72,V,1.05,V,1.48,V,2021-01-04
4,28,79,102,81,28079102_81_98,1.62,V,0.78,V,0.33,...,V,0.48,V,0.12,V,0.32,V,0.93,V,2021-01-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32288,28,79,59,89,28079059_89_98,0.00,V,0.00,V,0.00,...,V,0.00,V,0.00,V,0.00,V,0.00,V,2023-12-27
32289,28,79,59,89,28079059_89_98,0.00,V,0.00,V,0.00,...,V,0.00,V,0.00,V,0.00,V,0.00,V,2023-12-28
32290,28,79,59,89,28079059_89_98,0.00,V,0.00,V,0.00,...,V,0.00,V,0.00,V,0.00,V,0.00,V,2023-12-29
32291,28,79,59,89,28079059_89_98,0.00,V,0.00,V,0.00,...,V,0.00,V,0.00,V,0.00,V,0.00,V,2023-12-30
32292,28,79,59,89,28079059_89_98,0.00,V,0.00,V,0.00,...,V,0.00,V,0.00,V,0.00,V,0.00,V,2023-12-31

## Mapeo Magnitud

In [52]:
mapeo = {80: 'RAD_ULTRV', 
         81: 'VEL_VIENT',
         82: 'DIR_VIENT',
         83: 'TEMP',
         86: 'HUM_REL',
         87: 'PRES_BARIOMETRICA',
         88: 'RAD_SOL',
         89: 'PRECIPITACION',}

df['MAGNITUD'] = df['MAGNITUD'].map(mapeo)

df['MAGNITUD'].value_counts()

MAGNITUD
TEMP                 23236
HUM_REL              22006
PRECIPITACION         9972
VEL_VIENT             9745
DIR_VIENT             9745
RAD_SOL               7783
PRES_BARIOMETRICA     7684
Name: count, dtype: int64

## Eliminar Provincia y Municipio

In [53]:
df = df.drop(columns=['PROVINCIA', 'MUNICIPIO'])

## Eliminar datos no Validos

In [54]:
import numpy as np

def eliminar_contenido(df, v_column, h_column):
    # Obtener los índices donde v es N
    indices_v_F = df.loc[df[v_column] == 'N'].index
    # Eliminar el valor de las celdas
    df.loc[indices_v_F, h_column] = np.nan
    return df

In [55]:
df = eliminar_contenido(df, 'V01', 'H01')
df = eliminar_contenido(df, 'V02', 'H02')
df = eliminar_contenido(df, 'V03', 'H03')
df = eliminar_contenido(df, 'V04', 'H04')
df = eliminar_contenido(df, 'V05', 'H05')
df = eliminar_contenido(df, 'V06', 'H06')
df = eliminar_contenido(df, 'V07', 'H07')
df = eliminar_contenido(df, 'V08', 'H08')
df = eliminar_contenido(df, 'V09', 'H09')
df = eliminar_contenido(df, 'V10', 'H10')
df = eliminar_contenido(df, 'V11', 'H11')
df = eliminar_contenido(df, 'V12', 'H12')
df = eliminar_contenido(df, 'V13', 'H13')
df = eliminar_contenido(df, 'V14', 'H14')
df = eliminar_contenido(df, 'V15', 'H15')
df = eliminar_contenido(df, 'V16', 'H16')
df = eliminar_contenido(df, 'V17', 'H17')
df = eliminar_contenido(df, 'V18', 'H18')
df = eliminar_contenido(df, 'V19', 'H19')
df = eliminar_contenido(df, 'V20', 'H20')
df = eliminar_contenido(df, 'V21', 'H21')
df = eliminar_contenido(df, 'V22', 'H22')
df = eliminar_contenido(df, 'V23', 'H23')
df = eliminar_contenido(df, 'V24', 'H24')

## Eliminar columnas V

In [56]:
df = df.drop(columns=['V01', 'V02', 'V03', 'V04', 'V05', 'V06', 'V02', 'V08', 'V09', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24'])
df

,ESTACION,MAGNITUD,PUNTO_MUESTREO,H01,H02,H03,H04,H05,H06,H07,...,H16,H17,H18,H19,H20,H21,H22,H23,H24,FECHA
0,102,VEL_VIENT,28079102_81_98,0.98,1.40,1.55,1.40,0.87,1.40,0.92,...,3.28,3.63,3.03,3.17,2.83,3.65,2.13,0.97,0.58,2021-01-01
1,102,VEL_VIENT,28079102_81_98,1.18,1.65,1.17,1.17,1.43,0.90,1.43,...,3.20,1.93,1.43,1.10,1.30,1.22,0.38,0.45,0.75,2021-01-02
2,102,VEL_VIENT,28079102_81_98,0.62,0.55,0.73,0.52,1.08,1.42,1.12,...,3.08,3.00,2.50,1.22,1.92,1.53,2.20,1.80,1.27,2021-01-03
3,102,VEL_VIENT,28079102_81_98,1.93,1.82,0.72,1.45,1.17,1.20,1.87,...,2.35,1.55,2.55,2.12,1.20,1.10,1.72,1.05,1.48,2021-01-04
4,102,VEL_VIENT,28079102_81_98,1.62,0.78,0.33,0.38,0.47,0.53,0.60,...,1.08,1.00,1.07,0.53,0.30,0.48,0.12,0.32,0.93,2021-01-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32288,59,PRECIPITACION,28079059_89_98,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2023-12-27
32289,59,PRECIPITACION,28079059_89_98,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2023-12-28
32290,59,PRECIPITACION,28079059_89_98,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2023-12-29
32291,59,PRECIPITACION,28079059_89_98,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2023-12-30
32292,59,PRECIPITACION,28079059_89_98,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2023-12-31

# Normalizacion

### Pasar Hs a filas

In [57]:
df = pd.melt(df, 
                id_vars=['ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'FECHA'], 
                value_vars=['H01', 'H02', 'H03', 'H04', 'H05', 'H06', 'H07', 'H08', 'H09', 'H10', 'H11', 'H12', 'H13', 'H14', 'H15', 'H16', 'H17', 'H18', 'H19', 'H20', 'H21', 'H22', 'H23', 'H24'], 
                var_name='HORA', 
                value_name='VALOR')

df

         ESTACION       MAGNITUD  PUNTO_MUESTREO      FECHA HORA  VALOR
0             102      VEL_VIENT  28079102_81_98 2021-01-01  H01   0.98
1             102      VEL_VIENT  28079102_81_98 2021-01-02  H01   1.18
2             102      VEL_VIENT  28079102_81_98 2021-01-03  H01   0.62
3             102      VEL_VIENT  28079102_81_98 2021-01-04  H01   1.93
4             102      VEL_VIENT  28079102_81_98 2021-01-05  H01   1.62
...           ...            ...             ...        ...  ...    ...
2164099        59  PRECIPITACION  28079059_89_98 2023-12-27  H24   0.00
2164100        59  PRECIPITACION  28079059_89_98 2023-12-28  H24   0.00
2164101        59  PRECIPITACION  28079059_89_98 2023-12-29  H24   0.00
2164102        59  PRECIPITACION  28079059_89_98 2023-12-30  H24   0.00
2164103        59  PRECIPITACION  28079059_89_98 2023-12-31  H24   0.00

[2164104 rows x 6 columns]

### Pasar MAGNITUD a columnas

In [58]:
df['MAGNITUD'] = df['MAGNITUD'].astype(str)

df = df.pivot_table(index=['ESTACION', 'FECHA', 'HORA'], 
                            columns='MAGNITUD', 
                            values='VALOR',
                            aggfunc='first').reset_index()

df

MAGNITUD,ESTACION,FECHA,HORA,DIR_VIENT,HUM_REL,PRECIPITACION,PRES_BARIOMETRICA,RAD_SOL,TEMP,VEL_VIENT
0,4,2021-01-01,H01,NaN,NaN,NaN,NaN,NaN,3.5,NaN
1,4,2021-01-01,H02,NaN,NaN,NaN,NaN,NaN,3.2,NaN
2,4,2021-01-01,H03,NaN,NaN,NaN,NaN,NaN,3.8,NaN
3,4,2021-01-01,H04,NaN,NaN,NaN,NaN,NaN,3.7,NaN
4,4,2021-01-01,H05,NaN,NaN,NaN,NaN,NaN,3.5,NaN
...,...,...,...,...,...,...,...,...,...,...
578959,115,2023-12-31,H20,NaN,82.0,NaN,NaN,NaN,9.6,NaN
578960,115,2023-12-31,H21,NaN,83.0,NaN,NaN,NaN,9.3,NaN
578961,115,2023-12-31,H22,NaN,83.0,NaN,NaN,NaN,9.0,NaN
578962,115,2023-12-31,H23,NaN,81.0,NaN,NaN,NaN,8.6,NaN
578963,115,2023-12-31,H24,NaN,79.0,NaN,NaN,NaN,8.4,NaN

In [59]:
nan_percentage = (df.isna().mean() * 100).round(2)

print(nan_percentage)

MAGNITUD
ESTACION              0.00
FECHA                 0.00
HORA                  0.00
DIR_VIENT            62.23
HUM_REL              14.84
PRECIPITACION        61.58
PRES_BARIOMETRICA    70.85
RAD_SOL              70.15
TEMP                  9.87
VEL_VIENT            62.17
dtype: float64

> Bastantes valores NaN
>
> SIN ELIMINAR LOS DATOS NO VALIDOS BAJA UN POCO EL PORCENTAJE

## Pasar a formato numerico, si es necesario

In [60]:
columnas_a_numerico = ['DIR_VIENT', 'HUM_REL', 'PRECIPITACION', 'PRES_BARIOMETRICA', 'RAD_SOL', 'TEMP', 'VEL_VIENT']

for columna in columnas_a_numerico:
    if df[columna].dtype == 'object':  
        df[columna] = df[columna].str.replace(',', '.')  
        df[columna] = pd.to_numeric(df[columna], errors='coerce')  

df

MAGNITUD,ESTACION,FECHA,HORA,DIR_VIENT,HUM_REL,PRECIPITACION,PRES_BARIOMETRICA,RAD_SOL,TEMP,VEL_VIENT
0,4,2021-01-01,H01,NaN,NaN,NaN,NaN,NaN,3.5,NaN
1,4,2021-01-01,H02,NaN,NaN,NaN,NaN,NaN,3.2,NaN
2,4,2021-01-01,H03,NaN,NaN,NaN,NaN,NaN,3.8,NaN
3,4,2021-01-01,H04,NaN,NaN,NaN,NaN,NaN,3.7,NaN
4,4,2021-01-01,H05,NaN,NaN,NaN,NaN,NaN,3.5,NaN
...,...,...,...,...,...,...,...,...,...,...
578959,115,2023-12-31,H20,NaN,82.0,NaN,NaN,NaN,9.6,NaN
578960,115,2023-12-31,H21,NaN,83.0,NaN,NaN,NaN,9.3,NaN
578961,115,2023-12-31,H22,NaN,83.0,NaN,NaN,NaN,9.0,NaN
578962,115,2023-12-31,H23,NaN,81.0,NaN,NaN,NaN,8.6,NaN
578963,115,2023-12-31,H24,NaN,79.0,NaN,NaN,NaN,8.4,NaN

## Juntar Fecha y Hora

In [61]:
df['FECHA'] = pd.to_datetime(df['FECHA'])

def convertir_hora(hora):
    if hora == 'H24':
        return '00:00'
    else:
        return hora[1:] + ':00'

df['HORA'] = df['HORA'].apply(convertir_hora)

df['FECHA_HORA'] = df['FECHA'].dt.strftime('%Y-%m-%d') + ' ' + df['HORA']

df['FECHA_HORA'] = pd.to_datetime(df['FECHA_HORA'])
#df_meteo = df_meteo.sort_values(by='FECHA_HORA')

df = df.drop(columns=['FECHA', 'HORA'])

df

MAGNITUD,ESTACION,DIR_VIENT,HUM_REL,PRECIPITACION,PRES_BARIOMETRICA,RAD_SOL,TEMP,VEL_VIENT,FECHA_HORA
0,4,NaN,NaN,NaN,NaN,NaN,3.5,NaN,2021-01-01 01:00:00
1,4,NaN,NaN,NaN,NaN,NaN,3.2,NaN,2021-01-01 02:00:00
2,4,NaN,NaN,NaN,NaN,NaN,3.8,NaN,2021-01-01 03:00:00
3,4,NaN,NaN,NaN,NaN,NaN,3.7,NaN,2021-01-01 04:00:00
4,4,NaN,NaN,NaN,NaN,NaN,3.5,NaN,2021-01-01 05:00:00
...,...,...,...,...,...,...,...,...,...
578959,115,NaN,82.0,NaN,NaN,NaN,9.6,NaN,2023-12-31 20:00:00
578960,115,NaN,83.0,NaN,NaN,NaN,9.3,NaN,2023-12-31 21:00:00
578961,115,NaN,83.0,NaN,NaN,NaN,9.0,NaN,2023-12-31 22:00:00
578962,115,NaN,81.0,NaN,NaN,NaN,8.6,NaN,2023-12-31 23:00:00
578963,115,NaN,79.0,NaN,NaN,NaN,8.4,NaN,2023-12-31 00:00:00

## Reordenar y Exportar

In [62]:
df = df[['ESTACION', 'FECHA_HORA', 'TEMP', 'HUM_REL', 'PRECIPITACION', 'PRES_BARIOMETRICA', 'RAD_SOL', 'DIR_VIENT', 'VEL_VIENT']]
df

MAGNITUD,ESTACION,FECHA_HORA,TEMP,HUM_REL,PRECIPITACION,PRES_BARIOMETRICA,RAD_SOL,DIR_VIENT,VEL_VIENT
0,4,2021-01-01 01:00:00,3.5,NaN,NaN,NaN,NaN,NaN,NaN
1,4,2021-01-01 02:00:00,3.2,NaN,NaN,NaN,NaN,NaN,NaN
2,4,2021-01-01 03:00:00,3.8,NaN,NaN,NaN,NaN,NaN,NaN
3,4,2021-01-01 04:00:00,3.7,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2021-01-01 05:00:00,3.5,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
578959,115,2023-12-31 20:00:00,9.6,82.0,NaN,NaN,NaN,NaN,NaN
578960,115,2023-12-31 21:00:00,9.3,83.0,NaN,NaN,NaN,NaN,NaN
578961,115,2023-12-31 22:00:00,9.0,83.0,NaN,NaN,NaN,NaN,NaN
578962,115,2023-12-31 23:00:00,8.6,81.0,NaN,NaN,NaN,NaN,NaN
578963,115,2023-12-31 00:00:00,8.4,79.0,NaN,NaN,NaN,NaN,NaN

In [63]:
df.to_csv("datos/meteorologia2021_2023.csv")