# Datos contaminacion

## Juntar

In [1]:
import pandas as pd

df1 = pd.read_csv("datos/contaminacion/anio21/ene_mo21.csv", sep=';')
df2 = pd.read_csv("datos/contaminacion/anio21/feb_mo21.csv", sep=';')
df3 = pd.read_csv("datos/contaminacion/anio21/mar_mo21.csv", sep=';')
df4 = pd.read_csv("datos/contaminacion/anio21/abr_mo21.csv", sep=';')
df5 = pd.read_csv("datos/contaminacion/anio21/may_mo21.csv", sep=';')
df6 = pd.read_csv("datos/contaminacion/anio21/jun_mo21.csv", sep=';')
df7 = pd.read_csv("datos/contaminacion/anio21/jul_mo21.csv", sep=';')
df8 = pd.read_csv("datos/contaminacion/anio21/ago_mo21.csv", sep=';')
df9 = pd.read_csv("datos/contaminacion/anio21/sep_mo21.csv", sep=';')
df10 = pd.read_csv("datos/contaminacion/anio21/oct_mo21.csv", sep=';')
df11 = pd.read_csv("datos/contaminacion/anio21/nov_mo21.csv", sep=';')
df12 = pd.read_csv("datos/contaminacion/anio21/dic_mo21.csv", sep=';')

print(list(df1.columns) == list(df2.columns) == list(df3.columns) == list(df4.columns) == list(df5.columns) == list(df6.columns) == list(df7.columns) == list(df8.columns) == list(df9.columns) == list(df10.columns) == list(df11.columns) == list(df12.columns))

df2021 = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12], ignore_index=True)

del [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12]

df2021.shape

True

(48369, 56)

In [2]:
df1 = pd.read_csv("datos/contaminacion/anio22/ene_mo22.csv", sep=';')
df2 = pd.read_csv("datos/contaminacion/anio22/feb_mo22.csv", sep=';')
df3 = pd.read_csv("datos/contaminacion/anio22/mar_mo22.csv", sep=';')
df4 = pd.read_csv("datos/contaminacion/anio22/abr_mo22.csv", sep=';')
df5 = pd.read_csv("datos/contaminacion/anio22/may_mo22.csv", sep=';')
df6 = pd.read_csv("datos/contaminacion/anio22/jun_mo22.csv", sep=';')
df7 = pd.read_csv("datos/contaminacion/anio22/jul_mo22.csv", sep=';')
df8 = pd.read_csv("datos/contaminacion/anio22/ago_mo22.csv", sep=';')
df9 = pd.read_csv("datos/contaminacion/anio22/sep_mo22.csv", sep=';')
df10 = pd.read_csv("datos/contaminacion/anio22/oct_mo22.csv", sep=';')
df11 = pd.read_csv("datos/contaminacion/anio22/nov_mo22.csv", sep=';')
df12 = pd.read_csv("datos/contaminacion/anio22/dic_mo22.csv", sep=';')

print(list(df1.columns) == list(df2.columns) == list(df3.columns) == list(df4.columns) == list(df5.columns) == list(df6.columns) == list(df7.columns) == list(df8.columns) == list(df9.columns) == list(df10.columns) == list(df11.columns) == list(df12.columns))

df2022 = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12], ignore_index=True)

del [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12]

df2022.shape

True

(47223, 56)

In [3]:
df1 = pd.read_csv("datos/contaminacion/anio23/ene_mo23.csv", sep=';')
df2 = pd.read_csv("datos/contaminacion/anio23/feb_mo23.csv", sep=';')
df3 = pd.read_csv("datos/contaminacion/anio23/mar_mo23.csv", sep=';')
df4 = pd.read_csv("datos/contaminacion/anio23/abr_mo23.csv", sep=';')
df5 = pd.read_csv("datos/contaminacion/anio23/may_mo23.csv", sep=';')
df6 = pd.read_csv("datos/contaminacion/anio23/jun_mo23.csv", sep=';')
df7 = pd.read_csv("datos/contaminacion/anio23/jul_mo23.csv", sep=';')
df8 = pd.read_csv("datos/contaminacion/anio23/ago_mo23.csv", sep=';')
df9 = pd.read_csv("datos/contaminacion/anio23/sep_mo23.csv", sep=';')
df10 = pd.read_csv("datos/contaminacion/anio23/oct_mo23.csv", sep=';')
df11 = pd.read_csv("datos/contaminacion/anio23/nov_mo23.csv", sep=';')
df12 = pd.read_csv("datos/contaminacion/anio23/dic_mo23.csv", sep=';')

print(list(df1.columns) == list(df2.columns) == list(df3.columns) == list(df4.columns) == list(df5.columns) == list(df6.columns) == list(df7.columns) == list(df8.columns) == list(df9.columns) == list(df10.columns) == list(df11.columns) == list(df12.columns))

df2023 = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12], ignore_index=True)

del [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12]

df2023.shape

True

(47242, 56)

In [4]:
print(list(df2021.columns) == list(df2022.columns) == list(df2023.columns))

True

In [5]:
df = pd.concat([df2021, df2022, df2023])

del [df2021, df2022, df2023]

## Creación de la columna Fecha

In [6]:
df['FECHA'] = df['DIA'].astype(str) + '/' + df['MES'].astype(str) + '/' + df['ANO'].astype(str)

df = df.drop(columns=['ANO', 'MES', 'DIA'])

df['FECHA'] = pd.to_datetime(df['FECHA'], format='%d/%m/%Y')

df

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,H01,V01,H02,V02,H03,...,V20,H21,V21,H22,V22,H23,V23,H24,V24,FECHA
0,28,79,4,1,28079004_1_38,6.0,V,6.0,V,5.0,...,V,5.0,V,5.0,V,5.0,V,4.0,V,2021-01-01
1,28,79,4,1,28079004_1_38,4.0,V,4.0,V,4.0,...,V,6.0,V,6.0,V,6.0,V,5.0,V,2021-01-02
2,28,79,4,1,28079004_1_38,6.0,V,5.0,V,4.0,...,V,6.0,V,6.0,V,6.0,V,5.0,V,2021-01-03
3,28,79,4,1,28079004_1_38,5.0,V,4.0,V,4.0,...,V,6.0,V,5.0,V,5.0,V,5.0,V,2021-01-04
4,28,79,4,1,28079004_1_38,4.0,V,5.0,V,4.0,...,V,9.0,V,8.0,V,6.0,V,5.0,V,2021-01-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47237,28,79,60,14,28079060_14_6,20.0,V,18.0,V,14.0,...,V,18.0,V,17.0,V,23.0,V,18.0,V,2023-12-27
47238,28,79,60,14,28079060_14_6,14.0,V,11.0,V,11.0,...,V,35.0,V,32.0,V,27.0,V,25.0,V,2023-12-28
47239,28,79,60,14,28079060_14_6,24.0,V,19.0,V,15.0,...,V,13.0,V,11.0,V,12.0,V,15.0,V,2023-12-29
47240,28,79,60,14,28079060_14_6,16.0,V,12.0,V,19.0,...,V,18.0,V,22.0,V,29.0,V,20.0,V,2023-12-30
47241,28,79,60,14,28079060_14_6,17.0,V,27.0,V,41.0,...,V,36.0,V,34.0,V,51.0,V,54.0,V,2023-12-31

## Mapeo Magnitud

In [7]:
mapeo = {1: 'SO2',
         6: 'CO',
         7: 'NO',
         8: 'NO2',
         9: 'PM2_5',
         10: 'PM10',
         12: 'NOx',
         14: 'O3',
         20: 'TOL',
         30: 'BEN',
         35: 'EBE',
         37: 'MXY',
         38: 'PXY',
         39: 'OXY',
         42: 'TCH',
         43: 'CH4',
         44: 'NMHC'}

df['MAGNITUD'] = df['MAGNITUD'].map(mapeo)

df['MAGNITUD'].value_counts()

MAGNITUD
NO       25850
NO2      25850
NOx      25850
O3       14196
PM10     14141
PM2_5     8401
TOL       6432
BEN       6432
EBE       6432
SO2       4673
CO        4541
TCH         12
CH4         12
NMHC        12
Name: count, dtype: int64

## Eliminar Provincia y Municipio

In [8]:
df = df.drop(columns=['PROVINCIA', 'MUNICIPIO'])

## Eliminar datos no Validos

In [9]:
import numpy as np

def eliminar_contenido(df, v_column, h_column):
    # Obtener los índices donde v es N
    indices_v_F = df.loc[df[v_column] == 'N'].index
    # Eliminar el valor de las celdas
    df.loc[indices_v_F, h_column] = np.nan
    return df

In [10]:
df = eliminar_contenido(df, 'V01', 'H01')
df = eliminar_contenido(df, 'V02', 'H02')
df = eliminar_contenido(df, 'V03', 'H03')
df = eliminar_contenido(df, 'V04', 'H04')
df = eliminar_contenido(df, 'V05', 'H05')
df = eliminar_contenido(df, 'V06', 'H06')
df = eliminar_contenido(df, 'V07', 'H07')
df = eliminar_contenido(df, 'V08', 'H08')
df = eliminar_contenido(df, 'V09', 'H09')
df = eliminar_contenido(df, 'V10', 'H10')
df = eliminar_contenido(df, 'V11', 'H11')
df = eliminar_contenido(df, 'V12', 'H12')
df = eliminar_contenido(df, 'V13', 'H13')
df = eliminar_contenido(df, 'V14', 'H14')
df = eliminar_contenido(df, 'V15', 'H15')
df = eliminar_contenido(df, 'V16', 'H16')
df = eliminar_contenido(df, 'V17', 'H17')
df = eliminar_contenido(df, 'V18', 'H18')
df = eliminar_contenido(df, 'V19', 'H19')
df = eliminar_contenido(df, 'V20', 'H20')
df = eliminar_contenido(df, 'V21', 'H21')
df = eliminar_contenido(df, 'V22', 'H22')
df = eliminar_contenido(df, 'V23', 'H23')
df = eliminar_contenido(df, 'V24', 'H24')

## Eliminar columnas V

In [11]:
df = df.drop(columns=['V01', 'V02', 'V03', 'V04', 'V05', 'V06', 'V02', 'V08', 'V09', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24'])
df

,ESTACION,MAGNITUD,PUNTO_MUESTREO,H01,H02,H03,H04,H05,H06,H07,...,H16,H17,H18,H19,H20,H21,H22,H23,H24,FECHA
0,4,SO2,28079004_1_38,6.0,6.0,5.0,5.0,5.0,5.0,5.0,...,6.0,6.0,5.0,5.0,6.0,5.0,5.0,5.0,4.0,2021-01-01
1,4,SO2,28079004_1_38,4.0,4.0,4.0,4.0,3.0,3.0,3.0,...,8.0,9.0,8.0,8.0,7.0,6.0,6.0,6.0,5.0,2021-01-02
2,4,SO2,28079004_1_38,6.0,5.0,4.0,4.0,4.0,3.0,3.0,...,8.0,8.0,8.0,7.0,7.0,6.0,6.0,6.0,5.0,2021-01-03
3,4,SO2,28079004_1_38,5.0,4.0,4.0,4.0,4.0,4.0,4.0,...,7.0,7.0,7.0,6.0,6.0,6.0,5.0,5.0,5.0,2021-01-04
4,4,SO2,28079004_1_38,4.0,5.0,4.0,4.0,4.0,3.0,2.0,...,9.0,9.0,8.0,6.0,7.0,9.0,8.0,6.0,5.0,2021-01-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47237,60,O3,28079060_14_6,20.0,18.0,14.0,9.0,11.0,12.0,9.0,...,29.0,31.0,16.0,17.0,20.0,18.0,17.0,23.0,18.0,2023-12-27
47238,60,O3,28079060_14_6,14.0,11.0,11.0,10.0,19.0,14.0,7.0,...,23.0,22.0,18.0,20.0,25.0,35.0,32.0,27.0,25.0,2023-12-28
47239,60,O3,28079060_14_6,24.0,19.0,15.0,13.0,13.0,13.0,11.0,...,22.0,21.0,19.0,13.0,16.0,13.0,11.0,12.0,15.0,2023-12-29
47240,60,O3,28079060_14_6,16.0,12.0,19.0,12.0,11.0,10.0,10.0,...,41.0,44.0,23.0,15.0,16.0,18.0,22.0,29.0,20.0,2023-12-30
47241,60,O3,28079060_14_6,17.0,27.0,41.0,39.0,40.0,43.0,57.0,...,54.0,51.0,46.0,42.0,37.0,36.0,34.0,51.0,54.0,2023-12-31

# Normalizacion

### Pasar Hs a filas

In [12]:
df = pd.melt(df, 
                id_vars=['ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'FECHA'], 
                value_vars=['H01', 'H02', 'H03', 'H04', 'H05', 'H06', 'H07', 'H08', 'H09', 'H10', 'H11', 'H12', 'H13', 'H14', 'H15', 'H16', 'H17', 'H18', 'H19', 'H20', 'H21', 'H22', 'H23', 'H24'], 
                var_name='HORA', 
                value_name='VALOR')

df

         ESTACION MAGNITUD PUNTO_MUESTREO      FECHA HORA  VALOR
0               4      SO2  28079004_1_38 2021-01-01  H01    6.0
1               4      SO2  28079004_1_38 2021-01-02  H01    4.0
2               4      SO2  28079004_1_38 2021-01-03  H01    6.0
3               4      SO2  28079004_1_38 2021-01-04  H01    5.0
4               4      SO2  28079004_1_38 2021-01-05  H01    4.0
...           ...      ...            ...        ...  ...    ...
3428011        60       O3  28079060_14_6 2023-12-27  H24   18.0
3428012        60       O3  28079060_14_6 2023-12-28  H24   25.0
3428013        60       O3  28079060_14_6 2023-12-29  H24   15.0
3428014        60       O3  28079060_14_6 2023-12-30  H24   20.0
3428015        60       O3  28079060_14_6 2023-12-31  H24   54.0

[3428016 rows x 6 columns]

### Pasar MAGNITUD a columnas

In [13]:
df['MAGNITUD'] = df['MAGNITUD'].astype(str)

df = df.pivot_table(index=['ESTACION', 'FECHA', 'HORA'], 
                            columns='MAGNITUD', 
                            values='VALOR',
                            aggfunc='first').reset_index()

df

MAGNITUD,ESTACION,FECHA,HORA,BEN,CO,EBE,NO,NO2,NOx,O3,PM10,PM2_5,SO2,TOL
0,4,2021-01-01,H01,NaN,0.2,NaN,1.0,10.0,12.0,NaN,NaN,NaN,6.0,NaN
1,4,2021-01-01,H02,NaN,0.2,NaN,1.0,16.0,18.0,NaN,NaN,NaN,6.0,NaN
2,4,2021-01-01,H03,NaN,0.2,NaN,1.0,7.0,9.0,NaN,NaN,NaN,5.0,NaN
3,4,2021-01-01,H04,NaN,0.2,NaN,1.0,5.0,6.0,NaN,NaN,NaN,5.0,NaN
4,4,2021-01-01,H05,NaN,0.2,NaN,1.0,6.0,8.0,NaN,NaN,NaN,5.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615436,60,2023-12-31,H20,NaN,NaN,NaN,5.0,30.0,37.0,37.0,7.0,NaN,NaN,NaN
615437,60,2023-12-31,H21,NaN,NaN,NaN,6.0,35.0,44.0,36.0,7.0,NaN,NaN,NaN
615438,60,2023-12-31,H22,NaN,NaN,NaN,4.0,37.0,44.0,34.0,11.0,NaN,NaN,NaN
615439,60,2023-12-31,H23,NaN,NaN,NaN,2.0,20.0,23.0,51.0,9.0,NaN,NaN,NaN
615440,60,2023-12-31,H24,NaN,NaN,NaN,2.0,15.0,19.0,54.0,11.0,NaN,NaN,NaN

In [14]:
nan_percentage = (df.isna().mean() * 100).round(2)

print(nan_percentage)

MAGNITUD
ESTACION     0.00
FECHA        0.00
HORA         0.00
BEN         76.97
CO          83.90
EBE         76.74
NO           4.67
NO2          4.53
NOx          4.51
O3          48.17
PM10        48.82
PM2_5       69.51
SO2         83.53
TOL         77.04
dtype: float64

## Pasar a formato numerico, si es necesario

In [15]:
columnas_a_numerico = ['BEN', 'CO', 'EBE', 'NO', 'NO2', 'NOx', 'O3', 'PM10', 'PM2_5', 'SO2', 'TOL']

for columna in columnas_a_numerico:
    if df[columna].dtype == 'object':  
        df[columna] = df[columna].str.replace(',', '.')  
        df[columna] = pd.to_numeric(df[columna], errors='coerce')  

df

MAGNITUD,ESTACION,FECHA,HORA,BEN,CO,EBE,NO,NO2,NOx,O3,PM10,PM2_5,SO2,TOL
0,4,2021-01-01,H01,NaN,0.2,NaN,1.0,10.0,12.0,NaN,NaN,NaN,6.0,NaN
1,4,2021-01-01,H02,NaN,0.2,NaN,1.0,16.0,18.0,NaN,NaN,NaN,6.0,NaN
2,4,2021-01-01,H03,NaN,0.2,NaN,1.0,7.0,9.0,NaN,NaN,NaN,5.0,NaN
3,4,2021-01-01,H04,NaN,0.2,NaN,1.0,5.0,6.0,NaN,NaN,NaN,5.0,NaN
4,4,2021-01-01,H05,NaN,0.2,NaN,1.0,6.0,8.0,NaN,NaN,NaN,5.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615436,60,2023-12-31,H20,NaN,NaN,NaN,5.0,30.0,37.0,37.0,7.0,NaN,NaN,NaN
615437,60,2023-12-31,H21,NaN,NaN,NaN,6.0,35.0,44.0,36.0,7.0,NaN,NaN,NaN
615438,60,2023-12-31,H22,NaN,NaN,NaN,4.0,37.0,44.0,34.0,11.0,NaN,NaN,NaN
615439,60,2023-12-31,H23,NaN,NaN,NaN,2.0,20.0,23.0,51.0,9.0,NaN,NaN,NaN
615440,60,2023-12-31,H24,NaN,NaN,NaN,2.0,15.0,19.0,54.0,11.0,NaN,NaN,NaN

## Juntar Fecha y Hora

In [16]:
df['FECHA'] = pd.to_datetime(df['FECHA'])

def convertir_hora(hora):
    if hora == 'H24':
        return '00:00'
    else:
        return hora[1:] + ':00'

df['HORA'] = df['HORA'].apply(convertir_hora)

df['FECHA_HORA'] = df['FECHA'].dt.strftime('%Y-%m-%d') + ' ' + df['HORA']

df['FECHA_HORA'] = pd.to_datetime(df['FECHA_HORA'])
#df_meteo = df_meteo.sort_values(by='FECHA_HORA')

df = df.drop(columns=['FECHA', 'HORA'])

df

MAGNITUD,ESTACION,BEN,CO,EBE,NO,NO2,NOx,O3,PM10,PM2_5,SO2,TOL,FECHA_HORA
0,4,NaN,0.2,NaN,1.0,10.0,12.0,NaN,NaN,NaN,6.0,NaN,2021-01-01 01:00:00
1,4,NaN,0.2,NaN,1.0,16.0,18.0,NaN,NaN,NaN,6.0,NaN,2021-01-01 02:00:00
2,4,NaN,0.2,NaN,1.0,7.0,9.0,NaN,NaN,NaN,5.0,NaN,2021-01-01 03:00:00
3,4,NaN,0.2,NaN,1.0,5.0,6.0,NaN,NaN,NaN,5.0,NaN,2021-01-01 04:00:00
4,4,NaN,0.2,NaN,1.0,6.0,8.0,NaN,NaN,NaN,5.0,NaN,2021-01-01 05:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
615436,60,NaN,NaN,NaN,5.0,30.0,37.0,37.0,7.0,NaN,NaN,NaN,2023-12-31 20:00:00
615437,60,NaN,NaN,NaN,6.0,35.0,44.0,36.0,7.0,NaN,NaN,NaN,2023-12-31 21:00:00
615438,60,NaN,NaN,NaN,4.0,37.0,44.0,34.0,11.0,NaN,NaN,NaN,2023-12-31 22:00:00
615439,60,NaN,NaN,NaN,2.0,20.0,23.0,51.0,9.0,NaN,NaN,NaN,2023-12-31 23:00:00
615440,60,NaN,NaN,NaN,2.0,15.0,19.0,54.0,11.0,NaN,NaN,NaN,2023-12-31 00:00:00

## Reordenar y Exportar

In [17]:
df = df[['ESTACION', 'FECHA_HORA', 'NO', 'NO2', 'NOx', 'BEN', 'CO', 'EBE',  'O3', 'PM10', 'PM2_5', 'SO2', 'TOL']]
df

MAGNITUD,ESTACION,FECHA_HORA,NO,NO2,NOx,BEN,CO,EBE,O3,PM10,PM2_5,SO2,TOL
0,4,2021-01-01 01:00:00,1.0,10.0,12.0,NaN,0.2,NaN,NaN,NaN,NaN,6.0,NaN
1,4,2021-01-01 02:00:00,1.0,16.0,18.0,NaN,0.2,NaN,NaN,NaN,NaN,6.0,NaN
2,4,2021-01-01 03:00:00,1.0,7.0,9.0,NaN,0.2,NaN,NaN,NaN,NaN,5.0,NaN
3,4,2021-01-01 04:00:00,1.0,5.0,6.0,NaN,0.2,NaN,NaN,NaN,NaN,5.0,NaN
4,4,2021-01-01 05:00:00,1.0,6.0,8.0,NaN,0.2,NaN,NaN,NaN,NaN,5.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
615436,60,2023-12-31 20:00:00,5.0,30.0,37.0,NaN,NaN,NaN,37.0,7.0,NaN,NaN,NaN
615437,60,2023-12-31 21:00:00,6.0,35.0,44.0,NaN,NaN,NaN,36.0,7.0,NaN,NaN,NaN
615438,60,2023-12-31 22:00:00,4.0,37.0,44.0,NaN,NaN,NaN,34.0,11.0,NaN,NaN,NaN
615439,60,2023-12-31 23:00:00,2.0,20.0,23.0,NaN,NaN,NaN,51.0,9.0,NaN,NaN,NaN
615440,60,2023-12-31 00:00:00,2.0,15.0,19.0,NaN,NaN,NaN,54.0,11.0,NaN,NaN,NaN

In [18]:
df.to_csv("datos/contaminacion2021_2023.csv")