# Creación de la columna distritos en los Datos Contaminacion-Meteo

Creación de la columna Distrito manualmente, a partir de los datos que tengo en el excel, una vez con la columna distrito creada:

-> Juntar ubicaciones trafico con historico trafico, para obtener el distrito en el historico

-> Juntar por distrito el trafico con el resto de datos.

-> Ver si elimino las estaciones con pocas mediciones (notebook anterior)

In [9]:
import pandas as pd

df = pd.read_csv("datos/cont_meteo_juntos_2021_2024.csv")

df.drop(columns='Unnamed: 0', inplace=True)

df['ESTACION'].value_counts()

ESTACION
50    26232
60    26217
57    26213
38    26206
48    26196
56    26136
40    26125
18    26122
8     26070
58    26055
59    26035
17    26013
27    25979
54    25968
39    25941
55    25938
47    25915
49    25851
36    25844
24    25744
11    24825
35    24427
16    23662
4     21727
Name: count, dtype: int64

In [10]:
df

,ESTACION,FECHA_HORA,NO,NO2,NOx,BEN,CO,EBE,O3,PM10,PM2_5,SO2,TOL,TEMP,HUM_REL,PRECIPITACION,PRES_BARIOMETRICA,RAD_SOL,DIR_VIENT,VEL_VIENT
0,4,2021-01-01 01:00:00,1.0,10.0,12.0,NaN,0.2,NaN,NaN,NaN,NaN,6.0,NaN,3.5,NaN,NaN,NaN,NaN,NaN,NaN
1,4,2021-01-01 02:00:00,1.0,16.0,18.0,NaN,0.2,NaN,NaN,NaN,NaN,6.0,NaN,3.2,NaN,NaN,NaN,NaN,NaN,NaN
2,4,2021-01-01 03:00:00,1.0,7.0,9.0,NaN,0.2,NaN,NaN,NaN,NaN,5.0,NaN,3.8,NaN,NaN,NaN,NaN,NaN,NaN
3,4,2021-01-01 04:00:00,1.0,5.0,6.0,NaN,0.2,NaN,NaN,NaN,NaN,5.0,NaN,3.7,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2021-01-01 05:00:00,1.0,6.0,8.0,NaN,0.2,NaN,NaN,NaN,NaN,5.0,NaN,3.5,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615436,60,2023-12-31 20:00:00,5.0,30.0,37.0,NaN,NaN,NaN,37.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
615437,60,2023-12-31 21:00:00,6.0,35.0,44.0,NaN,NaN,NaN,36.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
615438,60,2023-12-31 22:00:00,4.0,37.0,44.0,NaN,NaN,NaN,34.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
615439,60,2023-12-31 23:00:00,2.0,20.0,23.0,NaN,NaN,NaN,51.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
615440,60,2023-12-31 00:00:00,2.0,15.0,19.0,NaN,NaN,NaN,54.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
import pandas as pd

# Define el diccionario de mapeo
mapeo_distritos = {
    1:	4,
    35:	1,
    4:	9,
    39:	8,
    8:	3,
    38:	6,
    11:	5,
    40:	18,
    16:	15,
    17:	17,
    18:	11,
    36:	14,
    24:	9,
    27:	21,
    47:	2,
    48:	4,
    49:	3,
    50:	5,
    54:	18,
    55:	21,
    56:	12,
    57:	16,
    58:	8,
    59:	21,
    60:	8
}

df['DISTRITO'] = df['ESTACION'].map(mapeo_distritos)

df

,ESTACION,FECHA_HORA,NO,NO2,NOx,BEN,CO,EBE,O3,PM10,...,SO2,TOL,TEMP,HUM_REL,PRECIPITACION,PRES_BARIOMETRICA,RAD_SOL,DIR_VIENT,VEL_VIENT,DISTRITO
0,4,2021-01-01 01:00:00,1.0,10.0,12.0,NaN,0.2,NaN,NaN,NaN,...,6.0,NaN,3.5,NaN,NaN,NaN,NaN,NaN,NaN,9
1,4,2021-01-01 02:00:00,1.0,16.0,18.0,NaN,0.2,NaN,NaN,NaN,...,6.0,NaN,3.2,NaN,NaN,NaN,NaN,NaN,NaN,9
2,4,2021-01-01 03:00:00,1.0,7.0,9.0,NaN,0.2,NaN,NaN,NaN,...,5.0,NaN,3.8,NaN,NaN,NaN,NaN,NaN,NaN,9
3,4,2021-01-01 04:00:00,1.0,5.0,6.0,NaN,0.2,NaN,NaN,NaN,...,5.0,NaN,3.7,NaN,NaN,NaN,NaN,NaN,NaN,9
4,4,2021-01-01 05:00:00,1.0,6.0,8.0,NaN,0.2,NaN,NaN,NaN,...,5.0,NaN,3.5,NaN,NaN,NaN,NaN,NaN,NaN,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615436,60,2023-12-31 20:00:00,5.0,30.0,37.0,NaN,NaN,NaN,37.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
615437,60,2023-12-31 21:00:00,6.0,35.0,44.0,NaN,NaN,NaN,36.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
615438,60,2023-12-31 22:00:00,4.0,37.0,44.0,NaN,NaN,NaN,34.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
615439,60,2023-12-31 23:00:00,2.0,20.0,23.0,NaN,NaN,NaN,51.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
615440,60,2023-12-31 00:00:00,2.0,15.0,19.0,NaN,NaN,NaN,54.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8

In [12]:
df['DISTRITO'].isna().sum()

0

In [13]:
df.columns

Index(['ESTACION', 'FECHA_HORA', 'NO', 'NO2', 'NOx', 'BEN', 'CO', 'EBE', 'O3',
       'PM10', 'PM2_5', 'SO2', 'TOL', 'TEMP', 'HUM_REL', 'PRECIPITACION',
       'PRES_BARIOMETRICA', 'RAD_SOL', 'DIR_VIENT', 'VEL_VIENT', 'DISTRITO'],
      dtype='object')

In [14]:
nuevo_orden = ['ESTACION','DISTRITO', 'FECHA_HORA', 'NO', 'NO2', 'NOx', 'BEN', 'CO', 'EBE', 'O3',
       'PM10', 'PM2_5', 'SO2', 'TOL', 'TEMP', 'HUM_REL', 'PRECIPITACION',
       'PRES_BARIOMETRICA', 'RAD_SOL', 'DIR_VIENT', 'VEL_VIENT']

df = df.reindex(columns=nuevo_orden)

df

,ESTACION,DISTRITO,FECHA_HORA,NO,NO2,NOx,BEN,CO,EBE,O3,...,PM2_5,SO2,TOL,TEMP,HUM_REL,PRECIPITACION,PRES_BARIOMETRICA,RAD_SOL,DIR_VIENT,VEL_VIENT
0,4,9,2021-01-01 01:00:00,1.0,10.0,12.0,NaN,0.2,NaN,NaN,...,NaN,6.0,NaN,3.5,NaN,NaN,NaN,NaN,NaN,NaN
1,4,9,2021-01-01 02:00:00,1.0,16.0,18.0,NaN,0.2,NaN,NaN,...,NaN,6.0,NaN,3.2,NaN,NaN,NaN,NaN,NaN,NaN
2,4,9,2021-01-01 03:00:00,1.0,7.0,9.0,NaN,0.2,NaN,NaN,...,NaN,5.0,NaN,3.8,NaN,NaN,NaN,NaN,NaN,NaN
3,4,9,2021-01-01 04:00:00,1.0,5.0,6.0,NaN,0.2,NaN,NaN,...,NaN,5.0,NaN,3.7,NaN,NaN,NaN,NaN,NaN,NaN
4,4,9,2021-01-01 05:00:00,1.0,6.0,8.0,NaN,0.2,NaN,NaN,...,NaN,5.0,NaN,3.5,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615436,60,8,2023-12-31 20:00:00,5.0,30.0,37.0,NaN,NaN,NaN,37.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
615437,60,8,2023-12-31 21:00:00,6.0,35.0,44.0,NaN,NaN,NaN,36.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
615438,60,8,2023-12-31 22:00:00,4.0,37.0,44.0,NaN,NaN,NaN,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
615439,60,8,2023-12-31 23:00:00,2.0,20.0,23.0,NaN,NaN,NaN,51.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
615440,60,8,2023-12-31 00:00:00,2.0,15.0,19.0,NaN,NaN,NaN,54.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.to_csv('datos/cont_meteo_juntos_2021_2024.csv', index=False)