# Organización datos de trafico

In [32]:
import pandas as pd

df_historico = pd.read_csv("datos/trafico/pruebas/historico12-2023.csv", sep=';')
df_ubicaciones = pd.read_csv("datos/trafico/pruebas/ubicacion_12-2023.csv", sep=';')

## Coincidencias ids

In [33]:
import numpy as np

In [34]:
valores_unicos_hist = df_historico['id'].unique()
valores_unicos_ubic = df_ubicaciones['id'].unique()

In [35]:
print(len(valores_unicos_hist))
print(len(valores_unicos_ubic))

1258
4894

Hay mas ubicaciones que en el historico

In [36]:
interseccion = np.intersect1d(valores_unicos_hist, valores_unicos_ubic)

len(interseccion)

1258

Bien, tengo todas las ubicaciones de los puntos donde se detecta el trafico.

## Mapa con las ubicaciones de los puntos de medida

In [37]:
filtro = df_ubicaciones['id'].isin(interseccion)

df = df_ubicaciones[filtro]

df

,tipo_elem,distrito,id,cod_cent,nombre,utm_x,utm_y,longitud,latitud
0,URB,4.0,3840,1001,Jose Ortega y Gasset E-O - Pº Castellana-Serrano,441.615.343.346.657,44.757.679.421.385,-36.883.232.754.856,404.305.018.691.825
1,URB,4.0,3841,1002,Jose Ortega y Gasset O-E - Serrano-Pº Castellana,441.705.882.339.595,447.576.968.733.175,-368.725.610.305.613,404.305.239.406.404
2,URB,1.0,3842,1003,Pº Recoletos N-S - Almirante-Prim,441.319.371.258.338,447.484.115.423.716,-36.917.268.449.043,404.221.320.929.972
3,URB,4.0,3843,1004,Pº Recoletos S-N - Pl. Cibeles- Recoletos,44.130.163.298.559,44.747.637.275.141,-369.192.878.230.734,404.214.333.442.836
4,URB,4.0,3844,1005,(AFOROS) Pº Castellana S-N - Eduardo Dato - P...,441.605.765.071.902,447.613.213.924.728,-368.846.965.033.102,404.337.820.578.943
...,...,...,...,...,...,...,...,...,...
4857,M30,12.0,3763,PM41301,PM41301,441.022.426.318.453,446.938.770.218.517,-369.472.183.155.491,403.729.835.769.889
4858,M30,12.0,3703,PM41302,PM41302,441.029.238.995.126,44.693.881.269.769,-369.464.162.703.605,403.729.878.857.775
4859,M30,12.0,3704,PM41351,PM41351,441.060.646.102.521,446.896.735.319.193,-369.423.279.561.982,403.691.995.410.418
4860,M30,12.0,3705,PM41451,PM41451,439.746.454.030.432,447.136.529.510.394,-370.993.796.845.397,40.390.707.487.804
4883,M30,8.0,3706,PM43022,PM43022,440.677.266.644.124,448.280.812.445.193,-370.003.998.990.118,404.938.563.322.915

In [38]:
# Eliminar las 12 posiciones empezando por detras de la cadena, eliminar el punto

def recortar_cadena(cadena):
    return cadena[:-12]

df['longitud'] = df['longitud'].apply(recortar_cadena)
df['latitud'] = df['latitud'].apply(recortar_cadena)

/var/folders/p9/nnj0ywtx27b7m3kq95j5n8mm0000gn/T/ipykernel_31620/4294088814.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['longitud'] = df['longitud'].apply(recortar_cadena)
/var/folders/p9/nnj0ywtx27b7m3kq95j5n8mm0000gn/T/ipykernel_31620/4294088814.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['latitud'] = df['latitud'].apply(recortar_cadena)

In [39]:
# Eliminar el punto

df['longitud'] = df['longitud'].apply(lambda x: x.replace('.', '') if isinstance(x, str) else x)

df['latitud'] = df['latitud'].apply(lambda x: x.replace('.', '') if isinstance(x, str) else x)

/var/folders/p9/nnj0ywtx27b7m3kq95j5n8mm0000gn/T/ipykernel_31620/703455617.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['longitud'] = df['longitud'].apply(lambda x: x.replace('.', '') if isinstance(x, str) else x)
/var/folders/p9/nnj0ywtx27b7m3kq95j5n8mm0000gn/T/ipykernel_31620/703455617.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['latitud'] = df['latitud'].apply(lambda x: x.replace('.', '') if isinstance(x, str) else x)

In [40]:
# Colocar el punto donde toca

def colocar_punto(cadena):
    if len(cadena) >= 3:
        return cadena[:2] + '.' + cadena[2:]
    else:
        return cadena

# Aplicar la función lambda para colocar un punto en la posición 3 de la columna seleccionada
df['longitud'] = df['longitud'].apply(colocar_punto)
df['latitud'] = df['latitud'].apply(colocar_punto)

df

/var/folders/p9/nnj0ywtx27b7m3kq95j5n8mm0000gn/T/ipykernel_31620/3539797956.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['longitud'] = df['longitud'].apply(colocar_punto)
/var/folders/p9/nnj0ywtx27b7m3kq95j5n8mm0000gn/T/ipykernel_31620/3539797956.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['latitud'] = df['latitud'].apply(colocar_punto)

,tipo_elem,distrito,id,cod_cent,nombre,utm_x,utm_y,longitud,latitud
0,URB,4.0,3840,1001,Jose Ortega y Gasset E-O - Pº Castellana-Serrano,441.615.343.346.657,44.757.679.421.385,-3.6883,40.4305
1,URB,4.0,3841,1002,Jose Ortega y Gasset O-E - Serrano-Pº Castellana,441.705.882.339.595,447.576.968.733.175,-3.68725,40.4305
2,URB,1.0,3842,1003,Pº Recoletos N-S - Almirante-Prim,441.319.371.258.338,447.484.115.423.716,-3.6917,40.4221
3,URB,4.0,3843,1004,Pº Recoletos S-N - Pl. Cibeles- Recoletos,44.130.163.298.559,44.747.637.275.141,-3.69192,40.4214
4,URB,4.0,3844,1005,(AFOROS) Pº Castellana S-N - Eduardo Dato - P...,441.605.765.071.902,447.613.213.924.728,-3.68846,40.4337
...,...,...,...,...,...,...,...,...,...
4857,M30,12.0,3763,PM41301,PM41301,441.022.426.318.453,446.938.770.218.517,-3.69472,40.3729
4858,M30,12.0,3703,PM41302,PM41302,441.029.238.995.126,44.693.881.269.769,-3.69464,40.3729
4859,M30,12.0,3704,PM41351,PM41351,441.060.646.102.521,446.896.735.319.193,-3.69423,40.3691
4860,M30,12.0,3705,PM41451,PM41451,439.746.454.030.432,447.136.529.510.394,-3.70993,40.390
4883,M30,8.0,3706,PM43022,PM43022,440.677.266.644.124,448.280.812.445.193,-3.70003,40.4938

In [41]:
import folium

# Crear un mapa centrado en unas coordenadas específicas
mapa = folium.Map(location=[40.41831, -3.70275], zoom_start=12)

for index, row in df.iterrows():
    folium.Marker(location=[row['latitud'], row['longitud']], popup=row['nombre']).add_to(mapa)


# Visualizar el mapa
mapa

# Prueba ver que el calculo del trafico este bien

In [1]:
import pandas as pd

df_traf = pd.read_csv("datos/trafico_calculado_intensidad_hora.csv")

df_traf

,Unnamed: 0,id,tipo_elem,distrito,fecha,intensidad
0,0,1009,C30,9.0,2022-12-01 09:00:00,420
1,1,1009,C30,9.0,2022-12-01 10:00:00,1680
2,2,1009,C30,9.0,2022-12-01 11:00:00,1680
3,3,1009,C30,9.0,2022-12-01 12:00:00,1680
4,4,1009,C30,9.0,2022-12-01 13:00:00,1680
...,...,...,...,...,...,...
70777069,70777069,11283,URB,5.0,2023-11-30 19:00:00,702
70777070,70777070,11283,URB,5.0,2023-11-30 20:00:00,519
70777071,70777071,11283,URB,5.0,2023-11-30 21:00:00,227
70777072,70777072,11283,URB,5.0,2023-11-30 22:00:00,142
70777073,70777073,11283,URB,5.0,2023-11-30 23:00:00,93

In [2]:
datos_red = pd.read_csv("datos/prueba_calculo_intensidad.csv")

datos_red

   Unnamed: 0    id tipo_elem  distrito                fecha  intensidad
0           0  1009       M30       9.0  2021-01-01 00:00:00        1068
1           1  1009       M30       9.0  2021-01-01 01:00:00        8472
2           2  1009       M30       9.0  2021-01-01 02:00:00        2064
3           3  1009       M30       9.0  2021-01-01 03:00:00         516
4           4  1009       M30       9.0  2021-01-01 04:00:00         372

In [10]:
filas_filtradas = df_traf.loc[(df_traf['id'] == 1009) & (df_traf['distrito'] == 9.0) & (df_traf['tipo_elem'] == 'M30')]
filas_filtradas
#Correcto

       Unnamed: 0    id tipo_elem  distrito                fecha  intensidad
9494         9494  1009       M30       9.0  2021-01-01 00:00:00        1068
9495         9495  1009       M30       9.0  2021-01-01 01:00:00        8472
9496         9496  1009       M30       9.0  2021-01-01 02:00:00        2064
9497         9497  1009       M30       9.0  2021-01-01 03:00:00         516
9498         9498  1009       M30       9.0  2021-01-01 04:00:00         372
...           ...   ...       ...       ...                  ...         ...
26275       26275  1009       M30       9.0  2022-12-01 05:00:00        1680
26276       26276  1009       M30       9.0  2022-12-01 06:00:00        1680
26277       26277  1009       M30       9.0  2022-12-01 07:00:00        1680
26278       26278  1009       M30       9.0  2022-12-01 08:00:00        1680
26279       26279  1009       M30       9.0  2022-12-01 09:00:00        1260

[16786 rows x 6 columns]